//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockstarSeating.TNWebSvc_StringInputs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1", ConfigurationName="TNWebSvc_StringInputs.TNWebServiceStringInputsSoap")]
    public interface TNWebServiceStringInputsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Event[] GetEvents(
                    string websiteConfigID, 
                    string numberOfEvents, 
                    string eventID, 
                    string eventName, 
                    string eventDate, 
                    string beginDate, 
                    string endDate, 
                    string venueID, 
                    string venueName, 
                    string stateProvDesc, 
                    string stateID, 
                    string cityZip, 
                    string nearZip, 
                    string parentCategoryID, 
                    string childCategoryID, 
                    string grandchildCategoryID, 
                    string performerID, 
                    string performerName, 
                    string noPerformers, 
                    string lowPrice, 
                    string highPrice, 
                    string modificationDate, 
                    string onlyMine, 
                    string whereClause, 
                    string orderByClause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TicketGroup[] GetTickets(string websiteConfigID, string numberOfRecords, string eventID, string lowPrice, string highPrice, string ticketGroupID, string requestedTixSplit, string whereClause, string orderByClause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Category[] GetCategories(string websiteConfigID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetCategoriesMasterList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Category[] GetCategoriesMasterList(string websiteConfigID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Country[] GetCountries(string websiteConfigID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetCountryByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RockstarSeating.TNWebSvc_StringInputs.Country GetCountryByID(string websiteConfigID, string countryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetEventPerformers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EventPerformer[] GetEventPerformers(string websiteConfigID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetPerformerByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Performer[] GetPerformerByCategory(string websiteConfigID, string parentCategoryID, string childCategoryID, string grandchildCategoryID, string hasEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetSublevelCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Category[] GetSublevelCategories(string websiteConfigID, string parentCategoryID, string childCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetVenue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Venue[] GetVenue(string websiteConfigID, string venueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetVenueConfigurations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VenueConfiguration[] GetVenueConfigurations(string websiteConfigID, string venueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetHighInventoryPerforme" +
            "rs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PerformerPercent[] GetHighInventoryPerformers(string websiteConfigID, string numReturned, string parentCategoryID, string childCategoryID, string grandchildCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetHighSalesPerformers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PerformerPercent[] GetHighSalesPerformers(string websiteConfigID, string numReturned, string parentCategoryID, string childCategoryID, string grandchildCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/SearchEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Event[] SearchEvents(string websiteConfigID, string searchTerms, string whereClause, string orderByClause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetStates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        States[] GetStates(string websiteConfigID, string countryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetPricingInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RockstarSeating.TNWebSvc_StringInputs.PricingInformation GetPricingInfo(string websiteConfigID, string eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/SearchPerformers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Performer[] SearchPerformers(string websiteConfigID, string searchTerms, string whereClause, string orderByClause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetPerformerByCategoryCo" +
            "mpressed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPerformerByCategoryCompressed(string websiteConfigID, string parentCategoryID, string childCategoryID, string grandchildCategoryID, string hasEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetEventsCompressed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEventsCompressed(
                    string websiteConfigID, 
                    string numberOfEvents, 
                    string eventID, 
                    string eventName, 
                    string eventDate, 
                    string beginDate, 
                    string endDate, 
                    string venueID, 
                    string venueName, 
                    string stateProvDesc, 
                    string stateID, 
                    string cityZip, 
                    string nearZip, 
                    string parentCategoryID, 
                    string childCategoryID, 
                    string grandchildCategoryID, 
                    string performerID, 
                    string performerName, 
                    string noPerformers, 
                    string lowPrice, 
                    string highPrice, 
                    string modificationDate, 
                    string onlyMine, 
                    string whereClause, 
                    string orderByClause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1/GetTicketsCompressed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTicketsCompressed(string websiteConfigID, string numberOfRecords, string eventID, string lowPrice, string highPrice, string ticketGroupID, string requestedTixSplit, string whereClause, string orderByClause);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class Event : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int childCategoryIDField;
        
        private string cityField;
        
        private int clicksField;
        
        private System.DateTime dateField;
        
        private string displayDateField;
        
        private int grandchildCategoryIDField;
        
        private int idField;
        
        private bool isWomensEventField;
        
        private string mapURLField;
        
        private string nameField;
        
        private int parentCategoryIDField;
        
        private string stateProvinceField;
        
        private int stateProvinceIDField;
        
        private string venueField;
        
        private System.Nullable<int> venueConfigurationIDField;
        
        private int venueIDField;
        
        private int countryIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ChildCategoryID {
            get {
                return this.childCategoryIDField;
            }
            set {
                this.childCategoryIDField = value;
                this.RaisePropertyChanged("ChildCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
                this.RaisePropertyChanged("Clicks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DisplayDate {
            get {
                return this.displayDateField;
            }
            set {
                this.displayDateField = value;
                this.RaisePropertyChanged("DisplayDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int GrandchildCategoryID {
            get {
                return this.grandchildCategoryIDField;
            }
            set {
                this.grandchildCategoryIDField = value;
                this.RaisePropertyChanged("GrandchildCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsWomensEvent {
            get {
                return this.isWomensEventField;
            }
            set {
                this.isWomensEventField = value;
                this.RaisePropertyChanged("IsWomensEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MapURL {
            get {
                return this.mapURLField;
            }
            set {
                this.mapURLField = value;
                this.RaisePropertyChanged("MapURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int ParentCategoryID {
            get {
                return this.parentCategoryIDField;
            }
            set {
                this.parentCategoryIDField = value;
                this.RaisePropertyChanged("ParentCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
                this.RaisePropertyChanged("StateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int StateProvinceID {
            get {
                return this.stateProvinceIDField;
            }
            set {
                this.stateProvinceIDField = value;
                this.RaisePropertyChanged("StateProvinceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> VenueConfigurationID {
            get {
                return this.venueConfigurationIDField;
            }
            set {
                this.venueConfigurationIDField = value;
                this.RaisePropertyChanged("VenueConfigurationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int VenueID {
            get {
                return this.venueIDField;
            }
            set {
                this.venueIDField = value;
                this.RaisePropertyChanged("VenueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
                this.RaisePropertyChanged("CountryID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class PricingInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ticketsAvailableField;
        
        private decimal highPriceField;
        
        private decimal lowPriceField;
        
        private decimal weightedAvgPriceField;
        
        private string eventNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ticketsAvailable {
            get {
                return this.ticketsAvailableField;
            }
            set {
                this.ticketsAvailableField = value;
                this.RaisePropertyChanged("ticketsAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal highPrice {
            get {
                return this.highPriceField;
            }
            set {
                this.highPriceField = value;
                this.RaisePropertyChanged("highPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal lowPrice {
            get {
                return this.lowPriceField;
            }
            set {
                this.lowPriceField = value;
                this.RaisePropertyChanged("lowPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal weightedAvgPrice {
            get {
                return this.weightedAvgPriceField;
            }
            set {
                this.weightedAvgPriceField = value;
                this.RaisePropertyChanged("weightedAvgPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string eventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("eventName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class States : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stateProvinceShortDescField;
        
        private string stateProvinceLongDescField;
        
        private int stateProvinceIDField;
        
        private string countryDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StateProvinceShortDesc {
            get {
                return this.stateProvinceShortDescField;
            }
            set {
                this.stateProvinceShortDescField = value;
                this.RaisePropertyChanged("StateProvinceShortDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateProvinceLongDesc {
            get {
                return this.stateProvinceLongDescField;
            }
            set {
                this.stateProvinceLongDescField = value;
                this.RaisePropertyChanged("StateProvinceLongDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StateProvinceID {
            get {
                return this.stateProvinceIDField;
            }
            set {
                this.stateProvinceIDField = value;
                this.RaisePropertyChanged("StateProvinceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CountryDesc {
            get {
                return this.countryDescField;
            }
            set {
                this.countryDescField = value;
                this.RaisePropertyChanged("CountryDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class PerformerPercent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal percentField;
        
        private Category categoryField;
        
        private string descriptionField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
                this.RaisePropertyChanged("Percent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Category Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string childCategoryDescriptionField;
        
        private int childCategoryIDField;
        
        private string grandchildCategoryDescriptionField;
        
        private int grandchildCategoryIDField;
        
        private string parentCategoryDescriptionField;
        
        private int parentCategoryIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ChildCategoryDescription {
            get {
                return this.childCategoryDescriptionField;
            }
            set {
                this.childCategoryDescriptionField = value;
                this.RaisePropertyChanged("ChildCategoryDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ChildCategoryID {
            get {
                return this.childCategoryIDField;
            }
            set {
                this.childCategoryIDField = value;
                this.RaisePropertyChanged("ChildCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GrandchildCategoryDescription {
            get {
                return this.grandchildCategoryDescriptionField;
            }
            set {
                this.grandchildCategoryDescriptionField = value;
                this.RaisePropertyChanged("GrandchildCategoryDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GrandchildCategoryID {
            get {
                return this.grandchildCategoryIDField;
            }
            set {
                this.grandchildCategoryIDField = value;
                this.RaisePropertyChanged("GrandchildCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ParentCategoryDescription {
            get {
                return this.parentCategoryDescriptionField;
            }
            set {
                this.parentCategoryDescriptionField = value;
                this.RaisePropertyChanged("ParentCategoryDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ParentCategoryID {
            get {
                return this.parentCategoryIDField;
            }
            set {
                this.parentCategoryIDField = value;
                this.RaisePropertyChanged("ParentCategoryID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class VenueConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int capacityField;
        
        private int idField;
        
        private string mapSiteField;
        
        private string mapURLField;
        
        private string typeDescriptionField;
        
        private int typeIDField;
        
        private int venueIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
                this.RaisePropertyChanged("Capacity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MapSite {
            get {
                return this.mapSiteField;
            }
            set {
                this.mapSiteField = value;
                this.RaisePropertyChanged("MapSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MapURL {
            get {
                return this.mapURLField;
            }
            set {
                this.mapURLField = value;
                this.RaisePropertyChanged("MapURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TypeDescription {
            get {
                return this.typeDescriptionField;
            }
            set {
                this.typeDescriptionField = value;
                this.RaisePropertyChanged("TypeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
                this.RaisePropertyChanged("TypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int VenueID {
            get {
                return this.venueIDField;
            }
            set {
                this.venueIDField = value;
                this.RaisePropertyChanged("VenueID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class Venue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string boxOfficePhoneField;
        
        private int capacityField;
        
        private string childRulesField;
        
        private string cityField;
        
        private string countryField;
        
        private string directionsField;
        
        private int idField;
        
        private string nameField;
        
        private string notesField;
        
        private int numberOfConfigurationsField;
        
        private string parkingField;
        
        private string publicTransportationField;
        
        private string rulesField;
        
        private string stateProvinceField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string uRLField;
        
        private string willCallField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BoxOfficePhone {
            get {
                return this.boxOfficePhoneField;
            }
            set {
                this.boxOfficePhoneField = value;
                this.RaisePropertyChanged("BoxOfficePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
                this.RaisePropertyChanged("Capacity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ChildRules {
            get {
                return this.childRulesField;
            }
            set {
                this.childRulesField = value;
                this.RaisePropertyChanged("ChildRules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Directions {
            get {
                return this.directionsField;
            }
            set {
                this.directionsField = value;
                this.RaisePropertyChanged("Directions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int NumberOfConfigurations {
            get {
                return this.numberOfConfigurationsField;
            }
            set {
                this.numberOfConfigurationsField = value;
                this.RaisePropertyChanged("NumberOfConfigurations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Parking {
            get {
                return this.parkingField;
            }
            set {
                this.parkingField = value;
                this.RaisePropertyChanged("Parking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PublicTransportation {
            get {
                return this.publicTransportationField;
            }
            set {
                this.publicTransportationField = value;
                this.RaisePropertyChanged("PublicTransportation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
                this.RaisePropertyChanged("Rules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
                this.RaisePropertyChanged("StateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("Street1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("Street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string WillCall {
            get {
                return this.willCallField;
            }
            set {
                this.willCallField = value;
                this.RaisePropertyChanged("WillCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class Performer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Category categoryField;
        
        private string descriptionField;
        
        private int idField;
        
        private int homeVenueIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Category Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int HomeVenueID {
            get {
                return this.homeVenueIDField;
            }
            set {
                this.homeVenueIDField = value;
                this.RaisePropertyChanged("HomeVenueID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class EventPerformer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eventIDField;
        
        private int performerIDField;
        
        private string performerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PerformerID {
            get {
                return this.performerIDField;
            }
            set {
                this.performerIDField = value;
                this.RaisePropertyChanged("PerformerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PerformerName {
            get {
                return this.performerNameField;
            }
            set {
                this.performerNameField = value;
                this.RaisePropertyChanged("PerformerName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbreviationField;
        
        private int idField;
        
        private string internationalPhoneCodeField;
        
        private string nameField;
        
        private string currencyTypeDescField;
        
        private string currencyTypeAbbrField;
        
        private decimal conversionToUSDField;
        
        private decimal conversionFromUSDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
                this.RaisePropertyChanged("Abbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InternationalPhoneCode {
            get {
                return this.internationalPhoneCodeField;
            }
            set {
                this.internationalPhoneCodeField = value;
                this.RaisePropertyChanged("InternationalPhoneCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CurrencyTypeDesc {
            get {
                return this.currencyTypeDescField;
            }
            set {
                this.currencyTypeDescField = value;
                this.RaisePropertyChanged("CurrencyTypeDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CurrencyTypeAbbr {
            get {
                return this.currencyTypeAbbrField;
            }
            set {
                this.currencyTypeAbbrField = value;
                this.RaisePropertyChanged("CurrencyTypeAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal ConversionToUSD {
            get {
                return this.conversionToUSDField;
            }
            set {
                this.conversionToUSDField = value;
                this.RaisePropertyChanged("ConversionToUSD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal ConversionFromUSD {
            get {
                return this.conversionFromUSDField;
            }
            set {
                this.conversionFromUSDField = value;
                this.RaisePropertyChanged("ConversionFromUSD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tnwebservices.ticketnetwork.com/tnwebservice/v3.1")]
    public partial class TicketGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eventIDField;
        
        private decimal facePriceField;
        
        private string highSeatField;
        
        private int idField;
        
        private bool isMineField;
        
        private string lowSeatField;
        
        private bool markedField;
        
        private string notesField;
        
        private int parentCategoryIDField;
        
        private int ratingField;
        
        private string ratingDescriptionField;
        
        private decimal retailPriceField;
        
        private string rowField;
        
        private int ticketQuantityField;
        
        private int[] validSplitsField;
        
        private string ticketGroupTypeField;
        
        private string currencyTypeAbbrField;
        
        private decimal convertedActualPriceField;
        
        private decimal actualPriceField;
        
        private string sectionField;
        
        private decimal wholesalePriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal FacePrice {
            get {
                return this.facePriceField;
            }
            set {
                this.facePriceField = value;
                this.RaisePropertyChanged("FacePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HighSeat {
            get {
                return this.highSeatField;
            }
            set {
                this.highSeatField = value;
                this.RaisePropertyChanged("HighSeat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsMine {
            get {
                return this.isMineField;
            }
            set {
                this.isMineField = value;
                this.RaisePropertyChanged("IsMine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LowSeat {
            get {
                return this.lowSeatField;
            }
            set {
                this.lowSeatField = value;
                this.RaisePropertyChanged("LowSeat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Marked {
            get {
                return this.markedField;
            }
            set {
                this.markedField = value;
                this.RaisePropertyChanged("Marked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ParentCategoryID {
            get {
                return this.parentCategoryIDField;
            }
            set {
                this.parentCategoryIDField = value;
                this.RaisePropertyChanged("ParentCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("Rating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RatingDescription {
            get {
                return this.ratingDescriptionField;
            }
            set {
                this.ratingDescriptionField = value;
                this.RaisePropertyChanged("RatingDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal RetailPrice {
            get {
                return this.retailPriceField;
            }
            set {
                this.retailPriceField = value;
                this.RaisePropertyChanged("RetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int TicketQuantity {
            get {
                return this.ticketQuantityField;
            }
            set {
                this.ticketQuantityField = value;
                this.RaisePropertyChanged("TicketQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public int[] ValidSplits {
            get {
                return this.validSplitsField;
            }
            set {
                this.validSplitsField = value;
                this.RaisePropertyChanged("ValidSplits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TicketGroupType {
            get {
                return this.ticketGroupTypeField;
            }
            set {
                this.ticketGroupTypeField = value;
                this.RaisePropertyChanged("TicketGroupType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string currencyTypeAbbr {
            get {
                return this.currencyTypeAbbrField;
            }
            set {
                this.currencyTypeAbbrField = value;
                this.RaisePropertyChanged("currencyTypeAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal convertedActualPrice {
            get {
                return this.convertedActualPriceField;
            }
            set {
                this.convertedActualPriceField = value;
                this.RaisePropertyChanged("convertedActualPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal ActualPrice {
            get {
                return this.actualPriceField;
            }
            set {
                this.actualPriceField = value;
                this.RaisePropertyChanged("ActualPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("Section");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal WholesalePrice {
            get {
                return this.wholesalePriceField;
            }
            set {
                this.wholesalePriceField = value;
                this.RaisePropertyChanged("WholesalePrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TNWebServiceStringInputsSoapChannel : RockstarSeating.TNWebSvc_StringInputs.TNWebServiceStringInputsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TNWebServiceStringInputsSoapClient : System.ServiceModel.ClientBase<RockstarSeating.TNWebSvc_StringInputs.TNWebServiceStringInputsSoap>, RockstarSeating.TNWebSvc_StringInputs.TNWebServiceStringInputsSoap {
        
        public TNWebServiceStringInputsSoapClient() {
        }
        
        public TNWebServiceStringInputsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TNWebServiceStringInputsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TNWebServiceStringInputsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TNWebServiceStringInputsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Event[] GetEvents(
                    string websiteConfigID, 
                    string numberOfEvents, 
                    string eventID, 
                    string eventName, 
                    string eventDate, 
                    string beginDate, 
                    string endDate, 
                    string venueID, 
                    string venueName, 
                    string stateProvDesc, 
                    string stateID, 
                    string cityZip, 
                    string nearZip, 
                    string parentCategoryID, 
                    string childCategoryID, 
                    string grandchildCategoryID, 
                    string performerID, 
                    string performerName, 
                    string noPerformers, 
                    string lowPrice, 
                    string highPrice, 
                    string modificationDate, 
                    string onlyMine, 
                    string whereClause, 
                    string orderByClause) {
            return base.Channel.GetEvents(websiteConfigID, numberOfEvents, eventID, eventName, eventDate, beginDate, endDate, venueID, venueName, stateProvDesc, stateID, cityZip, nearZip, parentCategoryID, childCategoryID, grandchildCategoryID, performerID, performerName, noPerformers, lowPrice, highPrice, modificationDate, onlyMine, whereClause, orderByClause);
        }
        
        public TicketGroup[] GetTickets(string websiteConfigID, string numberOfRecords, string eventID, string lowPrice, string highPrice, string ticketGroupID, string requestedTixSplit, string whereClause, string orderByClause) {
            return base.Channel.GetTickets(websiteConfigID, numberOfRecords, eventID, lowPrice, highPrice, ticketGroupID, requestedTixSplit, whereClause, orderByClause);
        }
        
        public Category[] GetCategories(string websiteConfigID) {
            return base.Channel.GetCategories(websiteConfigID);
        }
        
        public Category[] GetCategoriesMasterList(string websiteConfigID) {
            return base.Channel.GetCategoriesMasterList(websiteConfigID);
        }
        
        public Country[] GetCountries(string websiteConfigID) {
            return base.Channel.GetCountries(websiteConfigID);
        }
        
        public RockstarSeating.TNWebSvc_StringInputs.Country GetCountryByID(string websiteConfigID, string countryID) {
            return base.Channel.GetCountryByID(websiteConfigID, countryID);
        }
        
        public EventPerformer[] GetEventPerformers(string websiteConfigID) {
            return base.Channel.GetEventPerformers(websiteConfigID);
        }
        
        public Performer[] GetPerformerByCategory(string websiteConfigID, string parentCategoryID, string childCategoryID, string grandchildCategoryID, string hasEvent) {
            return base.Channel.GetPerformerByCategory(websiteConfigID, parentCategoryID, childCategoryID, grandchildCategoryID, hasEvent);
        }
        
        public Category[] GetSublevelCategories(string websiteConfigID, string parentCategoryID, string childCategoryID) {
            return base.Channel.GetSublevelCategories(websiteConfigID, parentCategoryID, childCategoryID);
        }
        
        public Venue[] GetVenue(string websiteConfigID, string venueID) {
            return base.Channel.GetVenue(websiteConfigID, venueID);
        }
        
        public VenueConfiguration[] GetVenueConfigurations(string websiteConfigID, string venueID) {
            return base.Channel.GetVenueConfigurations(websiteConfigID, venueID);
        }
        
        public PerformerPercent[] GetHighInventoryPerformers(string websiteConfigID, string numReturned, string parentCategoryID, string childCategoryID, string grandchildCategoryID) {
            return base.Channel.GetHighInventoryPerformers(websiteConfigID, numReturned, parentCategoryID, childCategoryID, grandchildCategoryID);
        }
        
        public PerformerPercent[] GetHighSalesPerformers(string websiteConfigID, string numReturned, string parentCategoryID, string childCategoryID, string grandchildCategoryID) {
            return base.Channel.GetHighSalesPerformers(websiteConfigID, numReturned, parentCategoryID, childCategoryID, grandchildCategoryID);
        }
        
        public Event[] SearchEvents(string websiteConfigID, string searchTerms, string whereClause, string orderByClause) {
            return base.Channel.SearchEvents(websiteConfigID, searchTerms, whereClause, orderByClause);
        }
        
        public States[] GetStates(string websiteConfigID, string countryID) {
            return base.Channel.GetStates(websiteConfigID, countryID);
        }
        
        public RockstarSeating.TNWebSvc_StringInputs.PricingInformation GetPricingInfo(string websiteConfigID, string eventID) {
            return base.Channel.GetPricingInfo(websiteConfigID, eventID);
        }
        
        public Performer[] SearchPerformers(string websiteConfigID, string searchTerms, string whereClause, string orderByClause) {
            return base.Channel.SearchPerformers(websiteConfigID, searchTerms, whereClause, orderByClause);
        }
        
        public string GetPerformerByCategoryCompressed(string websiteConfigID, string parentCategoryID, string childCategoryID, string grandchildCategoryID, string hasEvent) {
            return base.Channel.GetPerformerByCategoryCompressed(websiteConfigID, parentCategoryID, childCategoryID, grandchildCategoryID, hasEvent);
        }
        
        public string GetEventsCompressed(
                    string websiteConfigID, 
                    string numberOfEvents, 
                    string eventID, 
                    string eventName, 
                    string eventDate, 
                    string beginDate, 
                    string endDate, 
                    string venueID, 
                    string venueName, 
                    string stateProvDesc, 
                    string stateID, 
                    string cityZip, 
                    string nearZip, 
                    string parentCategoryID, 
                    string childCategoryID, 
                    string grandchildCategoryID, 
                    string performerID, 
                    string performerName, 
                    string noPerformers, 
                    string lowPrice, 
                    string highPrice, 
                    string modificationDate, 
                    string onlyMine, 
                    string whereClause, 
                    string orderByClause) {
            return base.Channel.GetEventsCompressed(websiteConfigID, numberOfEvents, eventID, eventName, eventDate, beginDate, endDate, venueID, venueName, stateProvDesc, stateID, cityZip, nearZip, parentCategoryID, childCategoryID, grandchildCategoryID, performerID, performerName, noPerformers, lowPrice, highPrice, modificationDate, onlyMine, whereClause, orderByClause);
        }
        
        public string GetTicketsCompressed(string websiteConfigID, string numberOfRecords, string eventID, string lowPrice, string highPrice, string ticketGroupID, string requestedTixSplit, string whereClause, string orderByClause) {
            return base.Channel.GetTicketsCompressed(websiteConfigID, numberOfRecords, eventID, lowPrice, highPrice, ticketGroupID, requestedTixSplit, whereClause, orderByClause);
        }
    }
}
